name: auvnet
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter libraries
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  intl: ^0.20.2
  dio: ^5.4.0

  # State management
  flutter_bloc: ^9.0.0
  provider: ^6.1.1
  get: ^4.7.2
  equatable: ^2.0.7

  # UI & layout
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  percent_indicator: ^4.2.4
  google_fonts: ^6.2.1
  insta_image_viewer: ^1.0.4
  table_calendar: ^3.1.3
  flutter_credit_card: ^4.1.0
  flutter_inappwebview: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Splash and device preview
  animated_splash_screen: ^1.3.0
  device_preview: ^1.2.0
  pull_to_refresh_flutter3: ^2.0.2
  google_sign_in: ^6.3.0
  html: ^0.15.6
  connectivity_plus: ^6.1.4
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.0+1
  carousel_slider: ^5.1.1
  firebase_auth: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/